---
- name: User Setup and Sudo Rights Configuration
  hosts: local
  become: true

  vars:
    users:
      - name: gadir
        sudo: true
      - name: john
        sudo: true
      - name: mary
        sudo: false
      - name: tim
        sudo: false

  tasks:
    - name: Ensure users exist
      ansible.builtin.user:
        name: "{{ item.name }}"
        shell: /bin/bash
        create_home: yes
      loop: "{{ users }}"

    - name: Add users with sudo rights
      ansible.builtin.user:
        name: "{{ item.name }}"
        groups: sudo
        append: yes
      when: item.sudo
      loop: "{{ users }}"

    - name: Remove users from sudo group if they shouldn't have sudo
      ansible.builtin.command: "gpasswd -d {{ item.name }} sudo"
      ignore_errors: yes  # This avoids failure if user isn't in the group
      when: not item.sudo
      loop: "{{ users }}"
